### PR TITLE
Fixing #43, #44

### PR DESCRIPTION
**Pull request by iTaybb**
Fixing #43, #44

### CODE REVIEW

**Comment by id** [comment]
Thanks for the contribution @iTaybb !

**Comment by id** [comment]
Waiting for CI.

**Comment by id** [comment]
Some failures, I'll take a look later today.

**Comment by iTaybb** [comment]
Ah. Too bad. I cant figure what went wrong in the test. Could you please help?

**Comment by id** [comment]
Sorry, my bad https://github.com/klarna/kastlex/commit/dbd120da6ca23349c17d761030a4896245f6f102.

Fixing.

**Comment by id** [comment]
@iTaybb could you apply this patch to your branch?

```
diff --git a/web/plug/ensure_permissions.ex b/web/plug/ensure_permissions.ex
index 928b181d..99efaae8 100644
--- a/web/plug/ensure_permissions.ex
+++ b/web/plug/ensure_permissions.ex
@@ -22,7 +22,10 @@ defmodule Kastlex.Plug.EnsurePermissions do
     end
   end
   defp check_permissions(_user, conn, opts) do
-    check_permissions(Kastlex.Users.get_anonymous(), conn, opts)
+    case Kastlex.Users.get_anonymous() do
+      false -> handle_perms_error("anonymous", conn, opts)
+      user -> check_permissions(user, conn, opts)
+    end
   end

   defp has_permissions?(:list_topics = action, "GET", user, _), do: Keyword.get(user, action, false)
```

**Comment by id** [comment]
Or I can push it to master but then you'll need to rebase

**Comment by iTaybb** [comment]
I'll push it. I'm afk so i'll do it tomorrow.

**Comment by id** [comment]
Thanks!

**Pull request merged**
