### PR TITLE
Add missing newline at the end of the metrics export

### PR DESCRIPTION
**Pull request by andrusha**
Also documented manual testing procedure.

Should I add docker-compose with kastlex + kafka + prometheus + kafkacat producers/consumers to simplify manual testing?

screen shot 2017-12-04 at 14 04 26

### CODE REVIEW

**Comment by id** [comment]
@andrusha yes, that'd be nice!

**Comment by id** [comment]
So you add the compose file, then we merge?

**Comment by andrusha** [comment]
@id my only concern is that it might get a bit complex. In order to make it work we would need:

1. `docker-compose.yml` to be able to run the whole thing, including `kafka`.
2. `Dockerfile` for `kastlex` itself. It would also need some kind of port forwarding, eg [socat](https://stackoverflow.com/questions/46099874/how-can-i-forward-a-port-from-one-docker-container-to-another), because kastlex expects kafka to be local.
3. `Dockerfile` for `prometheus`, as it needs to be pointed to correct `kastlex`.
4. `Dockerfile` for `kafkacat` and scripts to connect to `kafka` as consumer group and produce  messages to it.

Does it sound good?

**Comment by id** [comment]
Yes, sounds good to me.

**Pull request merged**
